#ifndef __ERROR_CODE_H
#define __ERROR_CODE_H

#include "stm32f10x.h"

typedef enum
{
	ERROR_CODE_E_NONE = 0,
	ERROR_CODE_W_PARAM_DEFAULT,
	ERROR_CODE_W_PARAM_REJECTED,
	ERROR_CODE_E_SENSOR_AIR_FAIL,
	ERROR_CODE_E_SENSOR_TANK_FAIL,
	ERROR_CODE_E_SENSOR_BASKET_FAIL,
	ERROR_CODE_E_I2C_A_FAIL,
	ERROR_CODE_E_I2C_B_FAIL,
	ERROR_CODE_E_I2C_C_FAIL,
	ERROR_CODE_E_TANK_LOW,
	ERROR_CODE_E_TANK_HIGH,
	ERROR_CODE_E_BASKET_LOW,
	ERROR_CODE_E_BASKET_HIGH,
	ERROR_CODE_E_WATER_JUMP,
	ERROR_CODE_E_PRESSURE_PHYSICAL,
	ERROR_CODE_E_UPPER_LIMIT,
	ERROR_CODE_E_LOWER_LIMIT,
	ERROR_CODE_E_LIMIT_MISMATCH,
	ERROR_CODE_E_POSITION_UNTRUSTED,
	ERROR_CODE_E_STALL,
	ERROR_CODE_E_SELF_TEST_FAIL,
	ERROR_CODE_E_MOTOR_RELEASED,
	ERROR_CODE_COUNT
} ErrorCode_t;

typedef enum
{
	ERROR_LEVEL_NONE = 0,
	ERROR_LEVEL_WARNING,
	ERROR_LEVEL_FAULT
} ErrorLevel_t;

#endif
